export const FakeData = [
    {"id": '1', "dish_name": "Tomato Soup", "image": "https://s3.przepisy.pl/przepisy3ii/img/variants/800x0/zupa-pomidorowa.jpg", "category": "Soup", "cuisine": "polish", "description": "product description", "ingredients": "tomato, water, pasta", "quantity": 12, "price": 10},
  {"id": '2', "dish_name": "Burger", "image": "https://polki.pl/foto/4_3_LARGE/domowy-hamburger-przepis-skladniki-i-przygotowanie-2350724.jpg", "category": "Main course", "cuisine": "american", "description": "product description", "ingredients": "bread, meat, cucumber", "quantity": 20, "price": 15},
  {"id": '3', "dish_name": "Pizza", "image": "https://fotokulinarnie.pl/wp-content/uploads/2021/02/IMG_4407-scaled.jpg?v=1612898493", "category": "Main course", "cuisine": "italian", "description": "product description", "ingredients": "tomato, meat, cucumber, wheat", "quantity": 5, "price": 22},
  {"id": '4', "dish_name": "Tofu", "image": "https://vegetitian.com/wp-content/uploads/2021/04/Piec-prostych-i-smacznych-sposobow-na-przygotowanie-tofu-1.jpg", "category": "Vegan", "cuisine": "japanese", "description": "product description", "ingredients": "some plants idk", "quantity": 20, "price": 8},
  {"id": '5', "dish_name": "Sushi", "image": "https://www.przyslijprzepis.pl/media/cache/big/uploads/media/recipe/0008/94/sushi-uramaki.jpeg", "category": "Main course", "cuisine": "japanese", "description": "product description", "ingredients": "fish, rice", "quantity": 10, "price": 30},
  {"id": '6', "dish_name": "Mixed Olives", "image": "https://www.justalittlebitofbacon.com/wp-content/uploads/2016/10/italian-marinated-olives-2.jpg", "category": "Starters", "cuisine": "european", "description": "product description", "ingredients": "olives", "quantity": 35, "price": 5},
  {"id": '7', "dish_name": "Gnocchi", "image": "https://cdn.galleries.smcloud.net/t/galleries/gf-zH9s-EDZt-zi8V_przepysznie-proste-gnocchi-z-kielbasa-z-patelni-szybkie-danie-dla-zaganianych-1920x1080-nocrop.jpg", "category": "Main Course", "cuisine": "italian", "description": "product description", "ingredients": "gnocchi, tomato, meat", "quantity": 14, "price": 20},
  {"id": '8', "dish_name": "Pappardelle allarabiatta", "image": "https://ocdn.eu/pulscms-transforms/1/9QHktkuTURBXy8yMTNkMTAyMS04YzlmLTRlODktOTM3Yi1iNjEyNjEwOWFkOWYuanBlZ5GTBc0EsM0CdA", "category": "Main Course", "cuisine": "italian", "description": "product description", "ingredients": "pappardelle, pepper, tomato", "quantity": 18, "price": 20},
  {"id": '9', "dish_name": "Lamb Rump", "image": "https://img.delicious.com.au/OrYAWjVa/del/2016/02/marco-pierre-whites-roasted-lamb-rump-a-la-provencale-27922-2.jpg", "category": "Main Course", "cuisine": "european", "description": "product description", "ingredients": "lamb, potato", "quantity": 6, "price": 30},
  {"id": '10', "dish_name": "Dark Chocolate Mousse", "image": "https://images.food52.com/26ArSuv_cmBKU1_vj2ji6-u8KqE=/1200x900/bdd0ad49-b4b5-490b-af78-1159eb1d1159--Vodka_Dark_Chocolate_Mousse.jpg", "category": "Dessert", "cuisine": "french", "description": "product description", "ingredients": "chocolate, cherries", "quantity": 10, "price": 10},
  {"id": '11', "dish_name": "Panna Cotta", "image": "https://www.wloskakuchnia.pl/wp-content/uploads/2019/12/panna-cotta.jpg", "category": "Dessert", "cuisine": "italian", "description": "product description", "ingredients": "cream, chocolate", "quantity": 12, "price": 10},
  {"id": '12', "dish_name": "Tiramisu", "image": "https://www.kwestiasmaku.com/sites/v123.kwestiasmaku.com/files/deser_tiramisu_0.jpg", "category": "Dessert", "cuisine": "italian", "description": "product description", "ingredients": "cream, chocolate, almonds", "quantity": 14, "price": 14}
]